"use client";
import { useState } from "react";
import { AlertCircle, DownloadCloud, Link2, Settings2 } from "lucide-react";
import { UrlInput } from "@/components/UrlInput";
import { MediaPreview } from "@/components/MediaPreview";
import { FormatSelector } from "@/components/FormatSelector";
import { CarouselGrid } from "@/components/CarouselGrid";
import type { MediaAnalysisResult } from "@/services/types";

export default function AnyDownload() { const [media, setMedia] = useState<MediaAnalysisResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function analyze(url: string) { setLoading(true); setError(""); setMedia(null); try { const response = await fetch("/api/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "Unable to analyze this link."); setMedia(result.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to analyze this link."); } finally { setLoading(false); } }
  return <main className="container py-20"><p className="eyebrow">AnyDownload / public media</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-[-0.07em] md:text-7xl">Bring a public link.<br /><span className="text-neutral-400">Keep control.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-neutral-600">Analyze public YouTube, Instagram, and TikTok links, then download individual media directly to your device. No ZIP archives.</p><section className="mt-12"><UrlInput onAnalyze={analyze} isLoading={loading} /></section>{error && <div role="alert" className="mx-auto mt-8 flex max-w-2xl gap-3 border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={18} />{error}</div>}{media && <section className="mx-auto mt-12 max-w-4xl space-y-6"><MediaPreview media={media} />{media.carouselItems?.length ? <CarouselGrid items={media.carouselItems} platform={media.platform} title={media.title} /> : <FormatSelector formats={media.formats} platform={media.platform} title={media.title} />}</section>} {!media && !error && <div className="mt-16 grid gap-4 border-t border-neutral-200 pt-8 md:grid-cols-3">{[[Link2, "Paste a link", "Use a public URL from a supported platform."], [Settings2, "Choose quality", "Select video, audio, image, or carousel items."], [DownloadCloud, "Download directly", "Media streams to your device, one item at a time."]].map(([Icon, title, copy]) => <div key={title as string} className="border-t border-neutral-300 pt-4"><Icon size={18} /><h2 className="mt-8 font-semibold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-neutral-500">{copy as string}</p></div>)}</div>}</main>;
}
